
{% set data = load_setup_py_data() %}

package:
    name: msd_pytorch
    version: {{ data['version'] }}

source:
    path: ../

build:
    number: '12'
    script_env:
      # Used to store multiple versions of the CUDA architecture;
      # Is used by torch from version 1.3 onwards..
      - TORCH_CUDA_ARCH_LIST

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - python
        - setuptools
        - pytorch {{pytorch}}
        - cudatoolkit {{cudatoolkit}}
        {% for dep in data['setup_requires'] %}
        - {{ dep.lower() }}
        {% endfor %}
    run:
        - python
        - {{ pin_compatible('pytorch', max_pin='x.x') }}
        - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
        # dependencies are defined in setup.py
        {% for dep in data['install_requires'] %}
        - {{ dep.lower() }}
        {% endfor %}

about:
    home: https://github.com/ahendriksen/msd_pytorch
    license_file: LICENSE.md
    summary: "An implementation of Mixed-Scale Dense networks in PyTorch. "

extra:
    maintainers:
        - Allard Hendriksen
