
{% set data = load_setup_py_data() %}

package:
  name: msd_pytorch
  # If this release is tagged, use bare version number. Otherwise,
  # append 'dev' to version number.
  # This scheme complies with PEP-386:
  # https://www.python.org/dev/peps/pep-0386/
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}
  version: {{ data['version'] }}
  {% else %}
  version: {{ data['version'] + "dev" }}
  {% endif %}

source:
  #
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py_{{ python }}_cuda_{{ cudatoolkit }}_pytorch_{{ pytorch }}
  script_env:
    # Used to store multiple versions of the CUDA architecture;
    # Is used by torch from version 1.3 onwards..
    - TORCH_CUDA_ARCH_LIST
    # Used to select the right version of nvcc
    - CUDA_HOME
    # Used to increase the number of concurrent compilations in the ninja build
    # step.
    - MAX_JOBS
  missing_dso_whitelist:
    - "*/libc10.so"             # This library is part of pytorch
    - "*/libtorch_cpu.so"       # This library is part of pytorch
    - "*/libtorch_python.so"    # This library is part of pytorch
    - "*/libc10_cuda.so"        # This library is part of pytorch

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # https://github.com/conda/conda-build/issues/4047
    - ccache
  host:
    - python
    - setuptools
    - pytorch {{pytorch}}
    - cudatoolkit {{cudatoolkit}}
    # Force downloading gpu packages for pytorch:
    - _pytorch_select=0.2
    {% for dep in data['setup_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python
    - {{ pin_compatible('pytorch', max_pin='x.x') }}
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

about:
  home: https://github.com/ahendriksen/msd_pytorch
  license_file: LICENSE.md
  summary: "An implementation of Mixed-Scale Dense networks in PyTorch. "

extra:
  maintainers:
    - Allard Hendriksen
